import requests
import streamlit as st
from PyPDF2 import PdfReader
from typing import Dict, Optional
from datetime import datetime
import json

# Set page config must be the first Streamlit command
st.set_page_config(page_title="DVCNotes", page_icon="📝", layout="wide")

# Initialize API key directly from secrets
api_key = st.secrets["ANTHROPIC_API_KEY"]

class NotesProcessor:
    def __init__(self, api_key):
        self.api_key = api_key
        self.base_url = "https://api.anthropic.com/v1/messages"
        self.headers = {
            "anthropic-version": "2023-06-01",
            "content-type": "application/json",
            "x-api-key": self.api_key
        }
        self.ccc_definitions = {
            "CalGETC": """California General Education Transfer Curriculum - A new general education pattern replacing both IGETC and CSU GE Breadth starting Fall 2025. Key features:
            - Creates a single, unified transfer pathway to both UC and CSU systems
            - Reduces required units from 37-39 to 34 units
            - Adds a new requirement in Ethnic Studies
            - Maintains rigorous academic standards while simplifying transfer
            - Designed to increase transfer rates and reduce excess units
            - Will be required for all CCC students entering in Fall 2025 or later who plan to transfer to UC/CSU""",
            
            "AB206": """Assembly Bill 206 - A California law expanding financial aid for undocumented students. Key components:
            - Provides state financial aid to California Dream Act students who are exempt from non-resident tuition
            - Removes the requirement to submit an affidavit about pursuing legalization
            - Makes undocumented students with a valid work permit eligible for Federal Work-Study
            - Effective January 1, 2024
            - Aims to increase college accessibility and affordability for undocumented students""",
            
            "FTES": """Full-Time Equivalent Student - A standardized workload/enrollment measurement equal to 525 hours of student instruction 
            (calculated as 15 class hours per week × 35-week academic year = 525 hours). 
            One FTES can be generated by:
            - One full-time student taking 15 units
            - Multiple part-time students whose enrollments combine to 15 units
            This measurement is used for college funding and enrollment reporting.""",
            
            "IGETC": """Intersegmental General Education Transfer Curriculum - A series of courses California community college students can complete to satisfy freshman/sophomore level general education requirements before transferring to most UCs and CSUs."""
        }

    def process_notes(self, text: str, meeting_type: str = "General") -> Optional[Dict]:
        """Process text using Anthropic API to generate strategically aligned meeting notes."""
        system_prompt = """You are DVCNotes, a specialized meeting notes assistant for DVC that connects discussions to institutional goals while providing clear narrative accounts of meetings. Create detailed notes that align with DVC's mission to "inspire, educate, and empower students to transform their lives and their communities."

        When writing notes:
        - Explain what actually happened, as if telling someone who was absent
        - Include who said what and how decisions were reached
        - Describe debates, concerns, and how they were resolved
        - Keep the chronological flow while organizing by topic
        - Use specific quotes or paraphrased statements when relevant
        - Explain the context behind decisions
        - Note any strong reactions or important dynamics

        # [Committee/Department] Meeting Notes: [Date]
        **Respectfully submitted by: [Note taker name]**

        ## Quick Strategic Overview
        Provide a narrative summary of how the meeting's key discussions and decisions connected to DVC's strategic goals:
        * Student Learning & Success - What specific discussions/decisions impacted this?
        * Equity & Institutional Culture - How were these considerations addressed?
        * Innovation & Strategic Growth - What new approaches were discussed?
        * Community Engagement & Partnerships - How were community needs considered?

        ## Meeting Flow and Key Points
        Provide a brief chronological overview of how the meeting progressed, including:
        - Initial discussions and tone
        - Major topic transitions
        - Key moments of debate or decision
        - Overall meeting dynamics

        ## Attendance
        * Present in person: [Names]
        * Present online: [Names]

        ## Formal Approvals
        Describe how each approval proceeded, including any discussion:
        1. Agenda Approval
            a. Motion by: [Name]
            b. Second: [Name]
            c. Outcome: [Result]
            d. Discussion points (if any)

        2. Previous Meeting Notes
            a. Motion by: [Name]
            b. Second: [Name]
            c. Outcome: [Result]
            d. Discussion points (if any)

        ## Key Discussions & Updates
        For each major topic, tell the story of the discussion:
        * **Topic**: [Clear title]
            - What initiated this discussion
            - Key points raised by participants (with attribution when possible)
            - Areas of agreement and disagreement
            - How decisions were reached
            - Strategic alignment (how this supports DVC goals)
            - Impact on student success
            - Requirements/deadlines
            - Resources needed
            - Who is responsible
            - Next steps

        For any programs/initiatives discussed:
        * **Program Name**:
            - How the topic was introduced
            - Main advocates and their reasoning
            - Concerns raised and how addressed
            - Purpose and goals
            - Alignment with college mission
            - Implementation timeline
            - Impact on students/faculty
            - Resource requirements
            - Success metrics
            - Contact person

        ## Action Items & Strategic Initiatives
        Tell the story of how each action item was determined:
        * **Action Required**:
            - How this action was identified
            - Discussion points leading to this decision
            - Strategic goal alignment
            - Responsible party
            - Timeline/deadline
            - Resources needed
            - Success measures
            - Follow-up plan

        ## Important Dates & Deadlines
        Explain the context and importance of each date:
        * **[Date]**: [Event/Deadline]
            - How this deadline was determined
            - Purpose
            - Strategic importance
            - Who needs to participate
            - Required preparation
            - Resources available
            - Contact person

        ## Committee Updates
        Describe how each committee presented their updates:
        * **[Committee Name]**:
            - Who presented
            - Key updates
            - How updates were received
            - Strategic initiatives
            - Action items
            - Alignment with college goals
            - Next steps
            - Contact person

        ## Future Planning
        Describe how these items were identified:
        * How topics for next meeting were determined
        * Long-term strategic initiatives discussed
        * Required preparation
        * Resource needs identified

        ## Resources & Support
        * Contact information
        * Available training discussed
        * Support services mentioned
        * Reference materials shared

        ## Key Terms & Definitions
        Only include this section if education terms or acronyms were used in the meeting. For each term used:
        * **[Term/Acronym]**:
            - Official CCC Definition
            - How it was used in this meeting's context
            - Why it matters for this discussion
            - Impact on students/college
            - Any related requirements or deadlines
            - Where to find more information

        Key DVC Strategic Goals to Reference:
        1. Student Learning & Success
        - Increase completion rates
        - Enhance support services
        - Improve student experience
        
        2. Equity & Institutional Culture
        - Promote inclusive practices
        - Address achievement gaps
        - Support diverse needs
        
        3. Innovation & Strategic Growth
        - Implement new technologies
        - Enhance programs
        - Improve processes
        
        4. Community Engagement
        - Build partnerships
        - Serve local needs
        - Enhance outreach

        Guidelines:
        - Write in a clear narrative style that tells the story of what happened
        - Explain discussions and decisions as if describing to someone who was absent
        - Include actual quotes or paraphrased statements from participants when relevant
        - Describe any debates, concerns, or alternative viewpoints raised
        - Capture the flow of conversation and how decisions were reached
        - Detail specific examples and scenarios discussed
        - Explain the context behind decisions and next steps
        - Note emotional elements like enthusiasm, concerns, or disagreements
        - Describe any visual presentations or data shown
        - Maintain chronological flow while organizing by topic
        - Connect discussions to DVC's mission and goals
        - Highlight equity considerations
        - Note student success impacts
        - Include strategic context
        - Only include and explain terms and acronyms that were actually used in the meeting
        - Provide full context
        - Track all deadlines
        - Note resource needs
        - Specify responsible parties
        - Include success metrics
        - Use clear formatting
        - Bold (**) key items"""

        try:
            data = {
                "model": "claude-3-sonnet-20240229",
                "max_tokens": 4096,
                "system": system_prompt,
                "messages": [
                    {
                        "role": "user",
                        "content": f"Please analyze this transcript and create detailed, strategically-aligned notes for a {meeting_type} meeting. Reference these official definitions when applicable: {self.ccc_definitions}\n\n{text}"
                    }
                ]
            }

            response = requests.post(
                self.base_url,
                headers=self.headers,
                json=data,
                timeout=60
            )
            
            response.raise_for_status()
            
            content = response.json()['content'][0]['text']
            return {
                "summary": content,
                "timestamp": datetime.now().isoformat(),
                "meeting_type": meeting_type
            }
                
        except requests.exceptions.Timeout:
            st.error("Request timed out. Please try again.")
        except requests.exceptions.RequestException as e:
            st.error(f"API Error: {str(e)}")
        except Exception as e:
            st.error(f"Error processing notes: {str(e)}")
        return None

def extract_text_from_pdf(file) -> str:
    """Extract text from a PDF file using PyPDF2."""
    try:
        reader = PdfReader(file)
        text = []
        for page in reader.pages:
            extracted_text = page.extract_text()
            if extracted_text:
                text.append(extracted_text)
        
        if not text:
            st.warning("No text could be extracted from the PDF. It might be scanned or protected.")
            return ""
            
        return "\n".join(text)
    except Exception as e:
        st.error(f"Error extracting PDF text: {str(e)}")
        return ""

def main():
    processor = NotesProcessor(api_key)

    # Enhanced Custom CSS for DVC branding
    st.markdown("""
        <style>
        /* Main theme colors matching DVC green */
        :root {
            --dvc-green-dark: #006341;
            --dvc-green-light: #A2D5C6;
            --dvc-gray: #666666;
        }
        
        /* Global styles */
        .stApp {
            background-color: #ffffff;
        }
        
        .main .block-container {
            padding-top: 2rem;
        }
        
        /* Headers */
        h1, h2, h3, h4 {
            color: var(--dvc-green-dark);
            font-weight: 600;
        }
        
        /* Title area */
        .app-title {
            background: linear-gradient(90deg, var(--dvc-green-dark), var(--dvc-green-light));
            padding: 3rem;
            border-radius: 15px;
            margin-bottom: 2rem;
            text-align: center;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }

        .black-text {
            color: #000000 !important;
        }
        </style>
    """, unsafe_allow_html=True)

    # Header with gradient background
    st.markdown("""
        <div class="app-title">
            <div class="black-text">
                <h1 style="margin:0;font-size:2.5rem;">DVCNotes</h1>
                <p style="margin:0.5rem 0 2rem 0;font-size:1.2rem;">An AI-driven tool that transforms meeting transcripts into comprehensive, strategically aligned summaries for DVC.</p>
                <h2 style="margin:1rem 0;font-size:1.5rem;">DVC Mission Statement</h2>
                <p style="margin:1rem 0;font-size:1.1rem;line-height:1.6;">
                    We inspire, educate, and empower students to transform their lives and their communities. 
                    We guide students to achieve their goals by awarding degrees and certificates, preparing them 
                    for transfer to four-year colleges and universities, facilitating entrance to and advancement 
                    in careers, and fostering personal growth.
                </p>
            </div>
        </div>
    """, unsafe_allow_html=True)

    # Meeting type selector
    meeting_type = st.selectbox(
        "Select Meeting Type",
        ["General", "Academic Senate", "Department", "Committee"]
    )

    # Input method selection
    input_method = st.radio("Choose input method:", ["Text", "PDF"])
    
    text_input = ""
    if input_method == "Text":
        text_input = st.text_area(
            "Paste your text here:",
            height=200,
            placeholder="Enter meeting transcript, lecture notes, or any text to process..."
        )
    else:
        uploaded_pdf = st.file_uploader("Upload a PDF file", type="pdf")
        if uploaded_pdf:
            text_input = extract_text_from_pdf(uploaded_pdf)
            if text_input:
                st.success("PDF successfully loaded!")
                with st.expander("View extracted text"):
                    st.text(text_input)

    col1, col2, col3 = st.columns([1, 2, 1])
    with col2:
        if st.button("✨ Generate Notes", use_container_width=True):
            if text_input and text_input.strip():
                with st.spinner("🔄 Processing your notes, please give me a couple of minutes (patience is virtue!)..."):
                    notes_data = processor.process_notes(text_input, meeting_type)
                    if notes_data:
                        st.markdown("### 📋 Generated Notes")
                        st.markdown(notes_data["summary"])
                        
            else:
                st.warning("Please enter some text to process.")

if __name__ == "__main__":
    main()
